on:
  push:
    branches: [ dev1 ]

jobs: 
    cicd:
        uses: durgeshnttdata/workflow-template/.github/workflows/workflow.yml@main
        with:
            appName: cicd-test
            
        secrets: inherit 
