name: Build Publish and Deploy to Sandbox
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Update pom version
      run: |
          mvn versions:set -DnewVersion=${{inputs.appVersion}} -DgenerateBackupPoms=false
          mvn versions:commit

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Publish to Exchange
      run: mvn clean deploy --settings .maven/settings.xml -DconnectedAppClientId=${{ secrets.CONNECTED_APP_CLIENT_ID }} -DconnectedAppClientSecret=${{ secrets.CONNECTED_APP_CLIENT_SECRET }} 
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
      
    - name: Deploy to runtime
      run: |
        mvn deploy --settings .maven/settings.xml -DmuleDeploy -Denv=${{vars.ENV}} -Dtarget=${{vars.TARGET}} -DconnectedAppClientId="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -DconnectedAppClientSecret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" 
