on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
    cicd:
        uses: durgeshnttdata/workflow-cicd/.github/workflows/workflow.yml@main
        with:
            appName: cicd-test
            appVersion: 1.0.${{ github.run_number }}
