on:
  push:
    tags: 
      - '*.stage*'
jobs: 
    cicd:
        uses: durgeshnttdata/workflow-template/.github/workflows/workflowProd.yml@main
        with:
            appName: cicd-test
            
        secrets: inherit 
