on:
  push:
    tags: 
      - v[0-9].*.*.stage*
jobs: 
    cicd:
        uses: durgeshnttdata/workflow-template/.github/workflows/workflowStage.yml@main
        with:
            appName: cicd-test
            
        secrets: inherit 
